### Import packages

In [1]:
import tensorflow as tf
import numpy as np
import retro                           # Retro Games in Gym

from skimage import transform
from skimage.color import rgb2gray

import matplotlib.pyplot as plt
from collections import deque
import random
import warnings
warnings.filterwarnings('ignore')

C:\Users\junta\Anaconda2\envs\py3\lib\site-packages\h5py\__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


### Create environment

In [2]:
"""
Before create my environment, I have to import the game into gym.retro since the game roms are not included.
Thanks to the contribution from Thomas Simonini and Ancheng Deng, import the games by following the procudures below.

1. Download zip file from http://www.atarimania.com/rom_collection_archive_atari_2600_roms.html
2. Unzip Roms.rar, there are two zipped files inside and continuely unzip ROMS.rar
3. Search 'Space Invaders', copy all the related files (5 in total) and paste them into a newly created folder
4. Open prompt and change the directory to the newly created folder
5. put "python -m retro.import ." in the command line and run (don't forget the point after 'import')

There you go, then we can continue create the game environment for the DQ-Learning
"""

env = retro.make(game='SpaceInvaders-Atari2600')

print("The state size of the frame is:", env.observation_space)
print("The action size is:", env.action_space.n)

possible_actions = np.array(np.identity(env.action_space.n, dtype=int).tolist())
print(possible_actions)

The state size of the frame is: Box(210, 160, 3)
The action size is: 8
[[1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 1]]


### Define the preprocessing functions